name: nur_pay
description: "Nur Pay Simple Banking Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #for change app package name
  change_app_package_name: ^1.1.0
  #for IOS
  cupertino_icons: ^1.0.2
  #for Svg image
  flutter_svg: ^2.0.9
  #for network requests
  http: ^1.2.0
  #for local db
  shared_preferences: ^2.2.2
  #state management
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  #for check internet or other connections
  connectivity_plus: ^6.0.3
  #for firebase
  firebase_messaging: ^14.9.1
  firebase_storage: ^11.7.4
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  #for local notifications
  flutter_local_notifications: ^17.0.0
  #for file download and other
  path_provider: ^2.0.0
  #for notifications time zone
  flutter_timezone: ^1.0.4
  #for permissions
  permission_handler: ^11.3.1
  #for send image to firebase
  image_picker: ^1.0.7
  #for responsive size
  my_utils:
    path: packages/my_utils
  lottie: ^3.1.0
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  #for local auth
  pinput: ^4.0.0
  local_auth: ^2.2.0
  flutter_styled_toast: ^2.2.1
  toast: ^0.3.0
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.otf
        - asset: assets/fonts/inter/Inter-Bold.otf
        - asset: assets/fonts/inter/Inter-Italic.otf
        - asset: assets/fonts/inter/Inter-Light.otf
        - asset: assets/fonts/inter/Inter-Medium.otf
        - asset: assets/fonts/inter/Inter-Regular.otf
        - asset: assets/fonts/inter/Inter-SemiBold.otf

